GET http://localhost:4000/user-api/users

###
GET http://localhost:4000/product-api/products

###
GET http://localhost:4000/user-api/users/pavan

###Create user
POST http://localhost:4000/user-api/new-user
Content-Type: application/json

{
    "username":"ravi",
    "password":"ravi",
    "email":"ravi@mail.com"  
}

###Login user
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
    "username":"ravi",
    "password":"ravi"  
}


###
PUT http://localhost:4000/user-api/user
Content-Type: application/json

{
    "username":"pavan",
    "email":"pavankumar@mail.com",
    "age":24

}




###
DELETE http://localhost:4000/user-api/users/pavan